/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainProgram;


import java.awt.*;

import event.EventMenuSelected;
import swing.PanelBorder;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author niebz
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */

    public main() {

        initComponents();
        init();


    }


    CardLayout cardLayout;
    private void init() {

        setBackground(new Color(0,0,0,0));
        Method.Escape( this );

        cardLayout = (CardLayout) card_panel.getLayout();
        cardLayout.show( card_panel,"dashboard" );
        sidebar.initMoving( this );
        sidebar.addEventMenuSelected( new EventMenuSelected() {
            @Override
            public void selected (int index) {
                if (index == 0) cardLayout.show( card_panel,"dashboard" );
                else if (index == 1) cardLayout.show( card_panel,"account");
                else if (index == 2) cardLayout.show( card_panel,"banking");
                else if (index == 3) cardLayout.show( card_panel,"aboutme");
                else {
                    loginPage lp = new loginPage();
                    lp.setVisible( true );
                    dispose();
                }
            }
        } );




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new swing.PanelBorder();
        sidebar = new component.Menu();
        card_panel = new swing.PanelBorder();
        dashboard = new swing.PanelBorder();
        show_balance = new component.Card();
        recent_panel = new swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new swing.Table();
        show_ac_panel = new swing.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new swing.Table();
        account = new swing.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        banking = new swing.PanelBorder();
        jLabel3 = new javax.swing.JLabel();
        aboutme = new swing.PanelBorder();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setSize(new java.awt.Dimension(900, 600));

        main_panel.setBackground(new java.awt.Color(232, 232, 255));
        main_panel.setForeground(new java.awt.Color(232, 232, 255));
        main_panel.setMinimumSize(new java.awt.Dimension(900, 600));
        main_panel.setPreferredSize(new java.awt.Dimension(900, 600));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        main_panel.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 600));

        card_panel.setBackground(new java.awt.Color(232, 232, 255));
        card_panel.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(232, 232, 255));
        dashboard.setToolTipText("");
        dashboard.setName(""); // NOI18N

        show_balance.setColor1(new java.awt.Color(151, 150, 232));
        show_balance.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        recent_panel.setBackground(new java.awt.Color(151, 150, 232));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recent Banking");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout recent_panelLayout = new javax.swing.GroupLayout(recent_panel);
        recent_panel.setLayout(recent_panelLayout);
        recent_panelLayout.setHorizontalGroup(
            recent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recent_panelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(recent_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        recent_panelLayout.setVerticalGroup(
            recent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recent_panelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        show_ac_panel.setBackground(new java.awt.Color(151, 150, 232));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("All Account");

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table2);

        javax.swing.GroupLayout show_ac_panelLayout = new javax.swing.GroupLayout(show_ac_panel);
        show_ac_panel.setLayout(show_ac_panelLayout);
        show_ac_panelLayout.setHorizontalGroup(
            show_ac_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(show_ac_panelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel5)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, show_ac_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        show_ac_panelLayout.setVerticalGroup(
            show_ac_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(show_ac_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(show_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(recent_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(show_ac_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(show_ac_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addComponent(show_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recent_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        card_panel.add(dashboard, "dashboard");

        account.setBackground(new java.awt.Color(232, 232, 255));

        jLabel2.setText("Account");

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel2)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel2)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        card_panel.add(account, "account");

        banking.setBackground(new java.awt.Color(232, 232, 255));

        jLabel3.setText("Banking");

        javax.swing.GroupLayout bankingLayout = new javax.swing.GroupLayout(banking);
        banking.setLayout(bankingLayout);
        bankingLayout.setHorizontalGroup(
            bankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankingLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel3)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        bankingLayout.setVerticalGroup(
            bankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankingLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel3)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        card_panel.add(banking, "banking");

        aboutme.setBackground(new java.awt.Color(232, 232, 255));

        jLabel4.setText("About Me");

        javax.swing.GroupLayout aboutmeLayout = new javax.swing.GroupLayout(aboutme);
        aboutme.setLayout(aboutmeLayout);
        aboutmeLayout.setHorizontalGroup(
            aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutmeLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel4)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        aboutmeLayout.setVerticalGroup(
            aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutmeLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel4)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        card_panel.add(aboutme, "aboutme");

        main_panel.add(card_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 670, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    public void ListvalueChanged (ListSelectionEvent e) {
//
//        int selectedIndex = sidebar.listMenu1.getSelectedIndex();
//
//
//        switch (selectedIndex) {
//            case 0:
//                main.tabbed.setSelectedIndex( 0 );
//                break;
//            case 1:
//                main.tabbed.setSelectedIndex( 1 );
//                break;
//            case 2:
//                main.tabbed.setSelectedIndex( 2 );
//                break;
//            case 3:
//                main.tabbed.setSelectedIndex( 3 );
//                break;
//            case 4:
//                loginPage lp = new loginPage();
//                this.dispose();
//                lp.setVisible( true );
//        }
//    }



    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.PanelBorder aboutme;
    private swing.PanelBorder account;
    private swing.PanelBorder banking;
    private swing.PanelBorder card_panel;
    private swing.PanelBorder dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private swing.PanelBorder main_panel;
    private swing.PanelBorder recent_panel;
    private swing.PanelBorder show_ac_panel;
    private component.Card show_balance;
    private component.Menu sidebar;
    private swing.Table table1;
    private swing.Table table2;
    // End of variables declaration//GEN-END:variables
}
