/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainProgram;


import java.awt.*;
import swing.PanelBorder;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author niebz
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public main() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        Method.Escape( this );


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new swing.PanelBorder();
        sidebar = new component.Menu();
        tabbed = new javax.swing.JTabbedPane();
        dashboard = new swing.PanelBorder();
        account = new swing.PanelBorder();
        banking = new swing.PanelBorder();
        aboutme = new swing.PanelBorder();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setSize(new java.awt.Dimension(900, 600));

        main_panel.setBackground(new java.awt.Color(232, 232, 255));
        main_panel.setForeground(new java.awt.Color(232, 232, 255));
        main_panel.setMinimumSize(new java.awt.Dimension(900, 600));
        main_panel.setPreferredSize(new java.awt.Dimension(900, 600));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        main_panel.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 600));

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        tabbed.addTab("Dashboard", dashboard);

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        tabbed.addTab("Account", account);

        javax.swing.GroupLayout bankingLayout = new javax.swing.GroupLayout(banking);
        banking.setLayout(bankingLayout);
        bankingLayout.setHorizontalGroup(
            bankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        bankingLayout.setVerticalGroup(
            bankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        tabbed.addTab("Banking", banking);

        javax.swing.GroupLayout aboutmeLayout = new javax.swing.GroupLayout(aboutme);
        aboutme.setLayout(aboutmeLayout);
        aboutmeLayout.setHorizontalGroup(
            aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        aboutmeLayout.setVerticalGroup(
            aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        tabbed.addTab("About Me", aboutme);

        main_panel.add(tabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 470, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sidebar.listMenu1.addListSelectionListener( new ListSelectionListener() {
            @Override
            public void valueChanged (ListSelectionEvent evt) {
                ListvalueChanged( evt );
            }
        } );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void ListvalueChanged (ListSelectionEvent e) {

        int selectedIndex = sidebar.listMenu1.getSelectedIndex();


        switch (selectedIndex) {
            case 0:
                main.tabbed.setSelectedIndex( 0 );
                break;
            case 1:
                main.tabbed.setSelectedIndex( 1 );
                break;
            case 2:
                main.tabbed.setSelectedIndex( 2 );
                break;
            case 3:
                main.tabbed.setSelectedIndex( 3 );
                break;
            case 4:
                loginPage lp = new loginPage();
                this.dispose();
                lp.setVisible( true );
        }
    }



    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.PanelBorder aboutme;
    private swing.PanelBorder account;
    private swing.PanelBorder banking;
    private swing.PanelBorder dashboard;
    private swing.PanelBorder main_panel;
    private component.Menu sidebar;
    public static javax.swing.JTabbedPane tabbed;
    // End of variables declaration//GEN-END:variables
}
