/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import swing.PanelBorder;

import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author niebz
 */
public class AC_Select_Card extends javax.swing.JPanel {

    /**
     * Creates new form AC_Select_Card
     */
    CardLayout current_parent;
    PanelBorder current_panel;
    private static final ArrayList<String> all_ac_number = new ArrayList<String>();
    private static int Index = 0 ;
    public AC_Select_Card(CardLayout parent_layout, PanelBorder parent_panel, String ac_bank_name, String ac_name, String ac_number, String ac_balance) {
        initComponents();
        setShow_ac_bank( ac_bank_name );
        setShow_ac_name( ac_name );
        setShow_ac_number( ac_number );
        all_ac_number.add( ac_number );
        setShow_ac_balance( ac_balance );
        setOpaque(false);
        current_parent = parent_layout;
        current_panel = parent_panel;
        Index = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        show_ac_bank = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        show_ac_name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        show_ac_number = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        show_ac_balance = new javax.swing.JLabel();
        next_ac_btn = new javax.swing.JLabel();
        previous_ac_btn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(185, 185, 195));
        setMaximumSize(new java.awt.Dimension(315, 320));
        setMinimumSize(new java.awt.Dimension(315, 320));
        setPreferredSize(new java.awt.Dimension(315, 320));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bank");

        show_ac_bank.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        show_ac_bank.setForeground(new java.awt.Color(255, 255, 255));
        show_ac_bank.setText("###AC_BANK###");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account Name");

        show_ac_name.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        show_ac_name.setForeground(new java.awt.Color(255, 255, 255));
        show_ac_name.setText("###AC_NAME###");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Account Number");

        show_ac_number.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        show_ac_number.setForeground(new java.awt.Color(255, 255, 255));
        show_ac_number.setText("###AC_NUMBER###");

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Balance");

        show_ac_balance.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        show_ac_balance.setForeground(new java.awt.Color(255, 255, 255));
        show_ac_balance.setText("###AC_BALANCE###");

        next_ac_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/next_right.png"))); // NOI18N
        next_ac_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next_ac_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_ac_btnMouseClicked(evt);
            }
        });

        previous_ac_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/next_left.png"))); // NOI18N
        previous_ac_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previous_ac_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previous_ac_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(previous_ac_btn)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(show_ac_balance)
                    .addComponent(jLabel1)
                    .addComponent(show_ac_bank)
                    .addComponent(jLabel3)
                    .addComponent(show_ac_name)
                    .addComponent(jLabel5)
                    .addComponent(show_ac_number))
                .addGap(40, 40, 40)
                .addComponent(next_ac_btn)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(previous_ac_btn)
                            .addComponent(next_ac_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(show_ac_bank, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(show_ac_name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(show_ac_number, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(show_ac_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void next_ac_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_ac_btnMouseClicked
        // TODO add your handling code here:
        current_parent.next(current_panel);
        Index+=1;
        if(Index == all_ac_number.size()) Index = 0;
    }//GEN-LAST:event_next_ac_btnMouseClicked

    private void previous_ac_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previous_ac_btnMouseClicked
        // TODO add your handling code here:
        current_parent.previous( current_panel );
        Index-=1;
        if ( Index < 0 ) Index = all_ac_number.size()-1;
    }//GEN-LAST:event_previous_ac_btnMouseClicked


    private void setShow_ac_bank(String bank_name){
        show_ac_bank.setText( bank_name );
    }

    private void setShow_ac_name(String ac_name){
        show_ac_name.setText( ac_name );
    }

    private void setShow_ac_number(String ac_number){
        show_ac_number.setText( ac_number );
    }

    private void setShow_ac_balance(String ac_balance){
        show_ac_balance.setText( ac_balance );
    }

    public static String get_showwing_ac_number (){
        return all_ac_number.get( Index );
    }

    public static void Reset_AC_number() {
        all_ac_number.clear();
    }

    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel next_ac_btn;
    private javax.swing.JLabel previous_ac_btn;
    private javax.swing.JLabel show_ac_balance;
    private javax.swing.JLabel show_ac_bank;
    private javax.swing.JLabel show_ac_name;
    private static javax.swing.JLabel show_ac_number;
    // End of variables declaration//GEN-END:variables
}
